
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.testlangpp.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 9;
  public static final int IDENT = 13;
  public static final int STATUS = 8;
  public static final int SEMI = 12;
  public static final int STRING = 14;
  public static final int EOF = 0;
  public static final int EXPECT = 7;
  public static final int TEST = 5;
  public static final int BASE_URL = 3;
  public static final int error = 1;
  public static final int GET = 6;
  public static final int EQUALS = 11;
  public static final int LET = 4;
  public static final int RBRACE = 10;
  public static final int CONFIG = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONFIG",
  "BASE_URL",
  "LET",
  "TEST",
  "GET",
  "EXPECT",
  "STATUS",
  "LBRACE",
  "RBRACE",
  "EQUALS",
  "SEMI",
  "IDENT",
  "STRING"
  };
}

